### ISSUE TITLE
no easy list of dependencies

### ISSUE THREAD

**Issue by awsomearvinder** [QuaKe8782/PartsBot#1]
Currently this project dosen't have a requirements.txt or any equivalent. This means you have to manually figure out what dependencies each file uses and install them, which is a pain.

I'll send a PR later just having a requirements.txt which has a list of deps, if that's ok?

**Comment by thefakequake** [comment]
i forgot these existed, thanks for helping out

**Comment by thefakequake** [comment]
Done.
