### ISSUE TITLE
Logo in project README points to an invalid URL

### ISSUE THREAD

**Issue by lukadd16** [QuaKe8782/PartsBot#9]
As the title (and image below) implies, the link for what should be a logo leads to a "Not Found" page.

![What I See](https://user-images.githubusercontent.com/58280822/107906730-d5688c00-6f1f-11eb-8a0e-64f9cb0889be.png)

**Comment by thefakequake** [comment]
Yeah, I noticed this. I still haven't found an image hosting platform that seems to display properly on MD.

**Comment by lukadd16** [comment]
Well the simple solution would be to just upload the logo directly to this repository. Then all you need to do is simply include the URL to this file (ex: https://github.com/QuaKe8782/PartsBot/blob/master/logo.jpg) within the README.

**Comment by thefakequake** [comment]
Good idea. Will do it now.
